### ISSUE TITLE
A commit that fixes some compilation errors and with some minor additions

### ISSUE THREAD

**Issue by OlivierSohn** [max0x7ba/atomic_queue#10]
Hello,

This commit contains fixes / additions that could be useful:
- cast fix (compilation error)
- move-construction fix (compilation error)
- enables the construction of 0-sized queues that do not allocate anything (usefull in my use case)
- a method to get the number of elements in the queue

https://github.com/OlivierSohn/atomic_queue/commit/2c819a080e70b855a0f2994aefd544a297acd740

**Comment by OlivierSohn** [comment]
Just to clarify, I won't have time to do a pull request with this, but if someone can incorporate those fixes / additions go ahead!

**Comment by max0x7ba** [comment]
No worries, I will incorporate your ideas.
