### ISSUE TITLE
could you please add some user guide for beginners?

### ISSUE THREAD

**Issue by 345161974** [max0x7ba/atomic_queue#11]
Hi, after check the benchmark page, I know this is another great high performance lock-free queue.
If I want to use this atomic_queue in my project, I found it's hard for me. It's better if you can provide a simple guide for beginners how to use atomic_queue just like moodycamel::ConcurrentQueue's doc include some basic use guide.
Thanks!

**Comment by dendisuhubdy** [comment]
This sounds like a good idea although it's a million $ question :)

**Comment by max0x7ba** [comment]
There are 3 things you can do with the queue:

1. Create.
2. Push.
3. Pop.

What exactly do you find hard?

**Comment by 345161974** [comment]
> There are 3 things you can do with the queue:
> 
> 1. Create.
> 2. Push.
> 3. Pop.
> 
> What exactly do you find hard?
Sorry for my poor c++ foundation, I should learn more about template in c++. I spent some time reading the benchmark code and know how to use atomic_queue gradually.
I mean maybe you can provide a simple demo to show how to use the atomic_queue specially. Now you show the usage in the benchmark file with other queue mixed.
As a beginner，I prefer moodycamel::ConcurrentQueue's doc as its simple use(header only) and simple usage doc. After reading the atomic_queque benchmark code, I don't konw how to use it directly😂, My C ++ foundation is too poor to understand your advanced code.
Finally I still want to appreciate you provide such great code, I will continue to study learning to use it.
