### ISSUE TITLE
Questions about evaluation graphs

### ISSUE THREAD

**Issue by junghan0611** [max0x7ba/atomic_queue#15]
1) In the 'A wait-free queue as fast as fetch-and-add paper', it shows the performances nearly 100 mops/seconds. But, the benchmark in this repo. shows 10 msgs/seconds (in case of XEON).
I know the environments are differ each others. But, why are they making differences? 

2) what is the major difference between AtomicQueue and OptimistAtomicQueue regarding to performance? It has a little change in the code, but it shows the performance large gap. 

3) Did you check the performance comparison with LRCQ? 
- LRCQ: Fast Concurrent Queues for x86 Processors, PPOPP '13

![image](https://user-images.githubusercontent.com/31724164/76692572-df5a7e80-662e-11ea-8c55-8dae068a9013.png) -- figure in wait-free queue paper

Thanks... 
Junghan

**Comment by max0x7ba** [comment]
Hi Junghan,

1. The queues are based on _ideas_ from the paper, but the implementation doesn't follow the paper. 

2. `OptimistAtomicQueue` busy-waits in `pop` and `push`  when empty or full, whereas `AtomicQueue` `try_pop` and `try_push` return `false` in such cases. That extra empty or full condition is handled by a CAS loop, rather than FAA.

3. I didn't.

**Comment by max0x7ba** [comment]
I got curious, downloaded LCRQ source code from http://mcg.cs.tau.ac.il/projects/lcrq/ and had a look into it.

Their benchmark is different. They measure the time of `N` threads each doing `enque`/`deque` pair of operations. Which means that in 1-thread case it is only 1 thread doing both `enque`/`deque` and that eliminates any contention and cache effects between different CPU cores. I do not think that is a reasonable usage scenario, in a 1-thread scenario a concurrent queue is never necessary. In multi-threaded scenario there is a chance that `enque`/`deque` operations often `deque` values `enque`d by this very thread.

I don't think such a benchmark represents realistic concurrent queue usage. The realistic usage, IMO, is when one thread is never both a producer and a consumer of the same queue object, rather a queue is a communication/distribution mechanism between different threads.
