### ISSUE TITLE
C++17 is needed in xenium

### ISSUE THREAD

**Issue by liesrock** [max0x7ba/atomic_queue#19]
Thanks for the amazing work! While following the installation steps, in one of the required dependency, i.e. xenium, https://github.com/mpoeter/xenium currently only support C++17.

Can you suggest the previous version/commit you used for the benchmarks (with C++14)?

**Comment by max0x7ba** [comment]
Thank you.

I wouldn't recommend using older versions because the latest version is the best.

I would comment out dependencies that don't compile.

**Comment by liesrock** [comment]
Ok, thanks for the prompt the answer: I will remove the dependencies which do not compile using C++14 for my Ubuntu 16.04 with Xenomai 3 tests.
