### ISSUE TITLE
Docs: optimistic version "busy-waits when empty or full", and what does the other do?

### ISSUE THREAD

**Issue by nunojpg** [max0x7ba/atomic_queue#25]
Something unclear to me while reading the README and also peeking at the code. So considering:

> AtomicQueue - a fixed size ring-buffer for atomic elements.
> OptimistAtomicQueue - a faster fixed size ring-buffer for atomic elements which busy-waits when empty or full.

What does AtomicQueue do when empty or full?

**Comment by max0x7ba** [comment]
The difference between `AtomicQueue` and `OptimistAtomicQueue` is that

*  `AtomicQueue` uses `try_push`/`try_pop` which return `false` when the queue if full/empty. 
* `OptimistAtomicQueue` uses `push`/`pop` which busy wait when the queue if full/empty.

**Comment by nunojpg** [comment]
You have that well explained in the README.

So maybe the confusion is that that API only exists for those versions? I.e. AtomicQueue does not have push/pop, and OptimisticAtomicQueue does not have try_*?

Because from the documentation I understood both version have all the 4 methods.

**Comment by max0x7ba** [comment]
> Because from the documentation I understood both version have all the 4 methods.

You are right, `AtomicQueue` class provides both versions, with and without `try_`. It is the usage that determines whether the queue is used in optimistic fashion, there is no `OptimistAtomicQueue` class template definition. In some cases you may want `push` and `try_pop`, i.e. optimistic producer, but pessimistic consumer.

**Comment by nunojpg** [comment]
Ok, thanks!
