### ISSUE TITLE
mention vcpkg package

### ISSUE THREAD

**Issue by mheyman** [max0x7ba/atomic_queue#29]
In the *Using the library* section, you can mention that atomic_queue is available via vcpkg. For example:

```sh
$ ./vcpkg install atomic-queue
```

FYI: the vcpkg port is pretty simple: https://github.com/microsoft/vcpkg/tree/master/ports/atomic-queue

**Comment by max0x7ba** [comment]
Added that to the documentation, thank you.

IMO, it would be least surprising if vcpkg port had exactly the same name - `atomic_queue` (with underscores, not dashes).

**Comment by mheyman** [comment]
Yes, it *would* be less surprising. Unfortunately, vcpkg is opinionated about package names and doesn't allow underscores :-(

**Comment by max0x7ba** [comment]
> Yes, it _would_ be less surprising. Unfortunately, vcpkg is opinionated about package names and doesn't allow underscores :-(

Oh, I didn't know that.

**Comment by max0x7ba** [comment]
> In the _Using the library_ section, you can mention that atomic_queue is available via vcpkg. For example:
> 
> ```shell
> $ ./vcpkg install atomic-queue
> ```
> 
> FYI: the vcpkg port is pretty simple: https://github.com/microsoft/vcpkg/tree/master/ports/atomic-queue

Would it be possible to make the vcpkg package update automatically when this repository updates? 

I shouldn't be advising users using an out-of-date version in the documentation.

**Comment by max0x7ba** [comment]
I wonder what is the process to keep the vcpkg package updated whenever there is a new version of this library in github, please?
