### ISSUE TITLE
Make benchmark dependencies optional in meson.build?

### ISSUE THREAD

**Issue by musicinmybrain** [max0x7ba/atomic_queue#31]
Consider allowing the tests to be built with meson even when the benchmark dependencies are not available.

Possible implementation: https://github.com/max0x7ba/atomic_queue/pull/30

**Comment by max0x7ba** [comment]
I don't have any experience with meson, so cannot comment on that. If you'd like to submit a pull request, then please do so.

**Comment by musicinmybrain** [comment]
This is solved by PR https://github.com/max0x7ba/atomic_queue/pull/30, which you just merged—so thanks! I’m closing the issue.
