### ISSUE TITLE
Implementations for ppc64le and s390x?

### ISSUE THREAD

**Issue by musicinmybrain** [max0x7ba/atomic_queue#33]
I’ve packaged this library for Fedora Linux as part of an effort to eventually package [sfizz](https://github.com/sfztools/sfizz/).

Both `ppc64le` (little-endian 64-bit PowerPC) and `s390x` (Linux on IBM Z) are supported primary architectures in Fedora. It’s fine that they aren’t supported here—we can just ensure that `atomic_queue` and any packages that depend on it aren’t built on those architectures.

Still, I wonder—is supporting these two architectures easy or difficult?

Unfortunately, I’m not entirely confident in the exact requirements of the `spin_loop_pause()` function, nor am I particularly familiar with the nuances of those two architectures, so it’s not easy for me to contribute implementations myself.

**Comment by musicinmybrain** [comment]
> If I had access to such machines I would be able to test it.

While I don’t have direct interactive shell access on these architectures, I can run the `atomic_queue` tests on them by doing RPM “scratch builds” on the Fedora builders. Does that help?

**Comment by max0x7ba** [comment]
Made some changes for you: https://github.com/max0x7ba/atomic_queue/commit/ee3d91cf131e56aa3302a43aeebf7b57a3c97b06

**Comment by musicinmybrain** [comment]
Thanks. I’ll run the tests right away, and I’ll investigate whether I can get the benchmarks (with their extra dependencies) to build as a one-time hack.

**Comment by max0x7ba** [comment]
> > "Unit tests with gcc" in GitHub CI runs `make -rj2 TOOLSET=gcc example run_tests`, it is intended to be invoked by continious integrations systems.
> 
> That should be the same as what I’m running via `meson test`, I think.

That's right.

> I did try to build and run the benchmarks (again, as a one-off, since even if the runtime isn’t too long, I don’t want to package three other queue implementations). It seems like I can’t run them at all without the `hugeadm` comands recommended in `README.md`.

It should run even if no `hudeadm` is installed and only issue a warning.
