### ISSUE TITLE
Could you add more apis such as Front() and PushFront()?

### ISSUE THREAD

**Issue by hahasofia** [max0x7ba/atomic_queue#35]
Dear author,
     I have a requirement such as to inquire the first element of queue but not pop it. It's just like what Front() does in std::vector.
     Also I want to push one element in the front of queue.
     Do you think these two functions Front and PushFront can be added in? Thank you.

**Comment by max0x7ba** [comment]
> Do you think these two functions `Front` and `PushFront` can be added in?

In a multi-threaded application `front` would return a reference to an element in the queue. By the time the element is examined, another thread may `pop` this element, leaving you with an invalid reference. For this reason `pop` is not an applicable use case for this non-blocking queue.

You may need to use a non-blocking queue which is based on hazard (smart) pointers, or use a blocking queue, e.g. `std::vector` with `std::mutex`.
