### ISSUE TITLE
Elaborate in docs what "atomic elements" means.

### ISSUE THREAD

**Issue by libbooze** [max0x7ba/atomic_queue#41]
I found this in source, 
but it was not obvious from reading the docs:

`        assert(std::atomic<T>{NIL}.is_lock_free()); // This queue is for atomic elements only. AtomicQueue2 is for non-atomic ones.`

I for one was thinking that maybe the `T `itself needs to be `std::atomic<SomeOtherT>`.

P.S. Not sure if that `assert `could be `static_assert`, IDK if there can be a type that is_lock_free but not constructible at compile time.

**Comment by max0x7ba** [comment]
> I for one was thinking that maybe the `T` itself needs to be `std::atomic<SomeOtherT>`.

`std::atomic<T>{NIL}.is_lock_free()` must be `true` for `T` to be considered _atomic_. You are right that the documentation wording may be less than ideal. I am open to your pull requests.

> I for one was thinking that maybe the `T` itself needs to be `std::atomic<SomeOtherT>`.

That calls for explicitly deleted queues partial specializations for `std::atomic<T>`, which makes good sense.

> Not sure if that `assert` could be `static_assert`, IDK if there can be a type that `is_lock_free` but not constructible at compile time.

`static_assert` would be ideal for that. https://en.cppreference.com/w/cpp/atomic/atomic/is_lock_free is not `constexpr`, sadly. C++17 offers another option https://en.cppreference.com/w/cpp/atomic/atomic/is_always_lock_free, which I may add in the future, unless someone submits a pull request for that earlier.

**Comment by max0x7ba** [comment]
Thank you for your pull request. 

I minimized the wording, added a few more words and moved the links to the bottom, and submitted a new commit only to not have to update yours.

**Comment by max0x7ba** [comment]
If you are happy you may like to close this issue. Otherwise, let me know.

**Comment by libbooze** [comment]
I like your changes better, thank you very much for fixing this.
