### ISSUE TITLE
'try_push' variant for move-only types

### ISSUE THREAD

**Issue by OlivierSohn** [max0x7ba/atomic_queue#5]
I adapted the queue so that it's compatible with move-only types (std::unique_ptr<T> for example)

I made minor modifications here and there (adding std::move on some assignments) and found that it would be usefull to have a try_push variant for moveable types, because if the push fails, for moveable types, the moved object is lost. In the variant I propose, the moved object is returned to the caller when the push fails:

```
    template<class T>
    std::optional<T> try_push_moveable(T&& element) noexcept {
        auto head = head_.load(X);
        if(Derived::spsc_) {
            if(static_cast<int>(head - tail_.load(X)) >= static_cast<int>(static_cast<Derived&>(*this).size_))
                return {std::forward<T>(element)};
            head_.store(head + 1, X);
        }
        else {
            do {
                if(static_cast<int>(head - tail_.load(X)) >= static_cast<int>(static_cast<Derived&>(*this).size_))
                    return {std::forward<T>(element)};
            } while(ATOMIC_QUEUE_UNLIKELY(!head_.compare_exchange_strong(head, head + 1, A, X))); // This loop is not FIFO.
        }

        static_cast<Derived&>(*this).do_push(std::forward<T>(element), head);
        return {};
    }
```

I'll submit a full pull request when I find some time to do it.

**Comment by max0x7ba** [comment]
It already supports move-only non-atomic types. 

Atomic types are assumed to be built-in fundamental types for which move is the same as copy.

**Comment by OlivierSohn** [comment]
> It already supports move-only non-atomic types.
> 
> Atomic types are assumed to be built-in fundamental types for which move is no different from copy.

That’s strange, I wonder why I needed to do changes. I’ll double check

**Comment by max0x7ba** [comment]
> That’s strange, I wonder why I needed to do changes. I’ll double check

Only `2` variants of the queue support non-atomic types.

Just [added a unit test for `std::unique_ptr`](https://github.com/max0x7ba/atomic_queue/commit/882e76a0a433cfe4cb06d71eae5074db80a57acd).

**Comment by OlivierSohn** [comment]
I'm using AtomicQueue**B**2 and with std::unique_ptr this is the compilation error I get (line 235 of atomic_queue.h):
`
error: object of type 'std::__1::unique_ptr<std::__1::vector<double, imajuscule::AlignedAllocator<double, imajuscule::Alignment::CACHE_LINE> >, std::__1::default_delete<std::__1::vector<double, imajuscule::AlignedAllocator<double, imajuscule::Alignment::CACHE_LINE> > > >' cannot be assigned because its copy assignment operator is implicitly deleted
            q_element = std::forward<U>(element);`

**Comment by OlivierSohn** [comment]
And I still think that the try_push api is not very move-only friendly, because if the try_push failed, there is no way to recover the object...

**Comment by max0x7ba** [comment]
> I'm using AtomicQueue**B**2 and with std::unique_ptr this is the compilation error I get (line 235 of atomic_queue.h):

Added [a move-only test for `AtomicQueueB2`}(https://github.com/max0x7ba/atomic_queue/commit/f35e3a58fd58e60814aff3eed13760d64de082b6).

**Comment by max0x7ba** [comment]
> cannot be assigned because its copy assignment operator is implicitly deleted `q_element`

Are you sure you didn't forget to call `move` for `try_push` argument?

**Comment by OlivierSohn** [comment]
> > cannot be assigned because its copy assignment operator is implicitly deleted `q_element`
> 
> Are you sure you didn't forget to call `move` for `try_push` argument?

You're right! Thanks
