### ISSUE TITLE
'optimist atomic queue' description is something different in read.md

### ISSUE THREAD

**Issue by jony999999** [max0x7ba/atomic_queue#50]
In your bench code(benchmarks.cc), Just 'AtomicQueue/AtomicQueue' is defined with retryDecorator (i.e. busy-waits).
and Optimist alias is not defined with retryDecorator.

**Comment by max0x7ba** [comment]
> In your bench code(benchmarks.cc), Just 'AtomicQueue/AtomicQueue' is defined with retryDecorator (i.e. busy-waits). and Optimist alias is not defined with retryDecorator.

Correct. And..?

**Comment by max0x7ba** [comment]
> In your bench code(benchmarks.cc), Just 'AtomicQueue/AtomicQueue' is defined with retryDecorator (i.e. busy-waits).
and Optimist alias is not defined with retryDecorator.

> OptimistAtomicQueue2 - a faster fixed size ring-buffer for non-atomic elements **which busy-waits when empty or full**.

I believe documentation covers your question in https://github.com/max0x7ba/atomic_queue#api in paragraph starting with "_Note that optimism ..._"
