### ISSUE TITLE
Atomics are not trivial

### ISSUE THREAD

**Issue by CurTInq** [max0x7ba/atomic_queue#66]
Thats it. It was [guaranteed](https://timsong-cpp.github.io/cppwp/n4659/atomics.types.int#2) that atomic integer specializations are trivially constructible until c++ 20, however [this is not the case anymore](https://eel.is/c++draft/atomics.types.int#2).
So this [static_assert](https://github.com/max0x7ba/atomic_queue/blob/master/include/atomic_queue/atomic_queue.h#L130) will fail starting with c++ 20
I ran into this while attempting to compile this under windows, microsoft stl library already follows the standard and reports assertion fail
https://godbolt.org/z/9WeonahxW

**Comment by max0x7ba** [comment]
Oh, that's news to me, thank you for bringing that to my attention. 

I'll have to bite the bullet and invoke the constructor, I guess 😬.
