### ISSUE TITLE
Benchmark comments

### ISSUE THREAD

**Issue by MasterBe** [max0x7ba/atomic_queue#69]
Can you please add some of your comments on the webpage? What do you think? Which to use for each case? And maybe an explanation of the difference in results if possible?

**Comment by max0x7ba** [comment]
I already wrote what I had to say.

The Internet needs more readers than writers, in my opinion.

**Comment by max0x7ba** [comment]
> Can you please add some of your comments on the webpage? What do you think? 

I don't think I have much else to add.

> Which to use for each case?

What cases do you have in mind?

> And maybe an explanation of the difference in results if possible?

The benchmark results are different because queue implementations are different.

**Comment by max0x7ba** [comment]
The best thing I can do for you is to defer to https://github.com/max0x7ba/atomic_queue#reading-material
