### ISSUE TITLE
Would you like to check one more lockfree mpmc queue?

### ISSUE THREAD

**Issue by erez-strauss** [max0x7ba/atomic_queue#7]
The  https://github.com/erez-strauss/lockfree_mpmc_queue/  is fast atomic lockfree mpmc queue.
The diff file:
[add_es_lockfree_mpmc_queue_20191123.diff.zip](https://github.com/max0x7ba/atomic_queue/files/3884859/add_es_lockfree_mpmc_queue_20191123.diff.zip)

Please let me know if you would like to have it included in the benchmarks.

**Comment by max0x7ba** [comment]
Thanks for your interest.

The other queues are in the benchmark because they are well known queues I would like to compare the performance of my queues against.

I am not interested in benchmarking any available queue on GitHub, I am sorry.

**Comment by amosbird** [comment]
what about queues in the folly lib? It's been the most efficient one iirc.

**Comment by max0x7ba** [comment]
> what about queues in the folly lib? 

Submit a pull request, I will have a look.

> It's been the most efficient one iirc.

I would like to see that benchmark.
