### ISSUE TITLE
Available in Conan

### ISSUE THREAD

**Issue by luizfeldmann** [max0x7ba/atomic_queue#71]
Hi,
First of all, thanks for this library.

I wanted to share that it's now available as a [package in conan](https://conan.io/center/recipes/atomic_queue?version=1.6.3).
As you already mention **vcpkg**, it might be a good idea to also mention **conan**, as it makes the library more accessible to a wider range of users. Plus, you get to use a cool badge:
[![Conan Center](https://img.shields.io/conan/v/atomic_queue)](https://conan.io/center/recipes/atomic_queue)

Best regards,

**Comment by max0x7ba** [comment]
Thank you for your kind contribution.

Would you like to update the README with the badge and brief Conan instructions for new users like me, please?

Maxim

**Comment by luizfeldmann** [comment]
Sure, here's a [PR](https://github.com/max0x7ba/atomic_queue/pull/72).

Because conan has somewhat of a learning curve, I'm linking to the official tutorials instead of leaving explicit instructions.

**Comment by max0x7ba** [comment]
Thank you ever so much for your kind contributions, Luiz.

**Comment by max0x7ba** [comment]
I wonder what is the process to keep the Conan package updated whenever there is a new version of this library in github, please?

**Comment by luizfeldmann** [comment]
The packages are kept up-to-date by the community. You or anyone may submit a [bump version](https://github.com/conan-io/conan-center-index/blob/master/docs/labels.md#bump-version) pull request adding the new version to [this file](https://github.com/conan-io/conan-center-index/blob/master/recipes/atomic_queue/all/conandata.yml). More instructions [here](https://github.com/conan-io/conan-center-index/blob/master/docs/bump_version.md). The new PR will be approved according to [these rules](https://github.com/conan-io/conan-center-index/blob/master/docs/review_process.md#rule-of-2-reviews). There is a [CI pipeline](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/README.md#the-build-service) which will build and test the new version when the PR is submitted. Packages for [multiple systems and compilers](https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md) are generated and made available automatically.
